default: &default
  adapter: postgresql
  encoding: UTF8
  timeout: 5000
  host: localhost
  reaping_frequency: 30
  username: dmizha
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: development
  password: <%= Rails.application.credentials.database[:user_pswd] %>

test:
  <<: *default
  database: test
  password: <%= Rails.application.credentials.database[:user_pswd] %>

production:
  <<: *default
  database: production
  username: dmizha
  password: <%= Rails.application.credentials.database[:user_pswd] %>
