default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: dmizha
  password: dmizha #<-- which you have defiend while installing postgresql
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rubydb

test:
  <<: *default
  database: rubydb

production:
  <<: *default
  database: rubydb
  username: dmizha
  password: dmizha
